<a href="https://colab.research.google.com/github/memeanji/python-bootcamp/blob/main/01_07)_%EB%8D%B0%EC%9D%B4%ED%84%B0%EA%B0%80%EA%B3%B5_%EB%82%A0%EC%A7%9C%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **날짜 다루기**


---

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

file_path = '/content/drive/MyDrive/data/temperatures.csv의 사본.csv'
data = pd.read_csv(file_path)

In [6]:
df = data.copy()

In [7]:
df.head()
#날짜별로 온도가 있는 간단한 데이터임

         Date  Temp
0  1981-01-01  20.7
1  1981-01-02  17.9
2  1981-01-03  18.8
3  1981-01-04  14.6
4  1981-01-05  15.8

In [8]:
df.info() # info를 통해서 어떤형식인지 확인하고

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3650 entries, 0 to 3649
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3650 non-null   object
 1   Temp    3650 non-null   float64
dtypes: float64(1), object(1)
memory usage: 57.2+ KB

## **문자형을 날짜형으로 변경**
- 날짜가 문자형으로 되어있다면 날짜형으로 변경해야 여러가지 날짜 계산을 할 수 있습니다.
- `pd.to_datetime(컬럼, format='날짜 형식')`

|형식|설명|
|:--|:--|
|%Y|0을 채운 4자리 연도|
|%y|0을 채운 2자리 연도|
|%m|0을 채운 월|
|%d|0을 채운 일|
|%H|0을 채운 시간|
|%M|0을 채운 분|
|%S|0을 채운 초|

In [9]:
# 날짜를 변경하고 싶으면 pd.to_datatime
pd.to_datetime(df['Date'], format='%Y-%m-%d')
#년월일이 - 을 통해서 연결어 있음

0      1981-01-01
1      1981-01-02
2      1981-01-03
3      1981-01-04
4      1981-01-05
          ...
3645   1990-12-27
3646   1990-12-28
3647   1990-12-29
3648   1990-12-30
3649   1990-12-31
Name: Date, Length: 3650, dtype: datetime64[ns]

In [10]:
df['Date1'] = pd.to_datetime(df['Date'], format='%Y-%m-%d')
df.info()

#format='%Y-%m-%d'이렇게 변환한 데이터를 새로운 컬럼에 넣어보고
# 기존컬럼은 object라는  dtype을 가지고 있지만
#새로운 컬럼은 datatime이라는 dtype을 가지고 있음

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3650 entries, 0 to 3649
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3650 non-null   object
 1   Temp    3650 non-null   float64
 2   Date1   3650 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 85.7+ KB

In [11]:
df.head()

         Date  Temp      Date1
0  1981-01-01  20.7 1981-01-01
1  1981-01-02  17.9 1981-01-02
2  1981-01-03  18.8 1981-01-03
3  1981-01-04  14.6 1981-01-04
4  1981-01-05  15.8 1981-01-05

## **날짜를 원하는 형식으로 변경**
`데이터컬럼.dt.strftime(날짜형식)`

In [12]:
df['Date1'].dt.strftime('%Y-%m')

#위에처럼 쓰면 년 월까지만 나오고

0       1981-01
1       1981-01
2       1981-01
3       1981-01
4       1981-01
         ...
3645    1990-12
3646    1990-12
3647    1990-12
3648    1990-12
3649    1990-12
Name: Date1, Length: 3650, dtype: object

In [13]:
df['Date1'].dt.strftime('%m-%d %H:%M')

# 시간분초가 들어있지 않아써 기본적으로 00시 00분으로 나오는걸 확인가능

0       01-01 00:00
1       01-02 00:00
2       01-03 00:00
3       01-04 00:00
4       01-05 00:00
           ...
3645    12-27 00:00
3646    12-28 00:00
3647    12-29 00:00
3648    12-30 00:00
3649    12-31 00:00
Name: Date1, Length: 3650, dtype: object

## **dt 연산자**
|연산자|설명|
|:--|:--|
|year|연도|
|month|월|
|day|일|
|dayofweek|요일(0-월요일, 6-일요일)|
|day_name()|요일을 문자열로|

In [14]:
df['year'] = df['Date1'].dt.year
df['month'] = df['Date1'].dt.month
df['day'] = df['Date1'].dt.day
df['dayofweek'] = df['Date1'].dt.dayofweek
df['dayname'] = df['Date1'].dt.day_name()

In [15]:
df.head()

         Date  Temp      Date1  year  month  day  dayofweek   dayname
0  1981-01-01  20.7 1981-01-01  1981      1    1          3  Thursday
1  1981-01-02  17.9 1981-01-02  1981      1    2          4    Friday
2  1981-01-03  18.8 1981-01-03  1981      1    3          5  Saturday
3  1981-01-04  14.6 1981-01-04  1981      1    4          6    Sunday
4  1981-01-05  15.8 1981-01-05  1981      1    5          0    Monday

## **날짜 계산**
- day 연산: `pd.Timedelta(day=숫자)`
- month 연산: `DateOffset(months=숫자)`
- year 연산: `DateOffset(years=숫자)`

In [16]:
df['plus day1'] = df['Date1'] + pd.Timedelta(days=1)
df.head()
#pandas의 Timedelta 함수를 사용하면 하루전후 한달전후 등 자유롭게 사용가능

,Date,Temp,Date1,year,month,day,dayofweek,dayname,plus day1
0,1981-01-01,20.7,1981-01-01,1981,1,1,3,Thursday,1981-01-02
1,1981-01-02,17.9,1981-01-02,1981,1,2,4,Friday,1981-01-03
2,1981-01-03,18.8,1981-01-03,1981,1,3,5,Saturday,1981-01-04
3,1981-01-04,14.6,1981-01-04,1981,1,4,6,Sunday,1981-01-05
4,1981-01-05,15.8,1981-01-05,1981,1,5,0,Monday,1981-01-06

In [17]:
df['plus day7'] = df['Date1'] + pd.Timedelta(days=7)
df.head()
#timedelta는 일자만 가능

,Date,Temp,Date1,year,month,day,dayofweek,dayname,plus day1,plus day7
0,1981-01-01,20.7,1981-01-01,1981,1,1,3,Thursday,1981-01-02,1981-01-08
1,1981-01-02,17.9,1981-01-02,1981,1,2,4,Friday,1981-01-03,1981-01-09
2,1981-01-03,18.8,1981-01-03,1981,1,3,5,Saturday,1981-01-04,1981-01-10
3,1981-01-04,14.6,1981-01-04,1981,1,4,6,Sunday,1981-01-05,1981-01-11
4,1981-01-05,15.8,1981-01-05,1981,1,5,0,Monday,1981-01-06,1981-01-12

In [18]:
df['minus day7'] = df['Date1'] - pd.Timedelta(days=7)
df.head()

,Date,Temp,Date1,year,month,day,dayofweek,dayname,plus day1,plus day7,minus day7
0,1981-01-01,20.7,1981-01-01,1981,1,1,3,Thursday,1981-01-02,1981-01-08,1980-12-25
1,1981-01-02,17.9,1981-01-02,1981,1,2,4,Friday,1981-01-03,1981-01-09,1980-12-26
2,1981-01-03,18.8,1981-01-03,1981,1,3,5,Saturday,1981-01-04,1981-01-10,1980-12-27
3,1981-01-04,14.6,1981-01-04,1981,1,4,6,Sunday,1981-01-05,1981-01-11,1980-12-28
4,1981-01-05,15.8,1981-01-05,1981,1,5,0,Monday,1981-01-06,1981-01-12,1980-12-29

In [19]:
from pandas.tseries.offsets import DateOffset

df['plus month1'] = df['Date1'] + DateOffset(months=1)
df.head()
#한달을 더해줌

,Date,Temp,Date1,year,month,day,dayofweek,dayname,plus day1,plus day7,minus day7,plus month1
0,1981-01-01,20.7,1981-01-01,1981,1,1,3,Thursday,1981-01-02,1981-01-08,1980-12-25,1981-02-01
1,1981-01-02,17.9,1981-01-02,1981,1,2,4,Friday,1981-01-03,1981-01-09,1980-12-26,1981-02-02
2,1981-01-03,18.8,1981-01-03,1981,1,3,5,Saturday,1981-01-04,1981-01-10,1980-12-27,1981-02-03
3,1981-01-04,14.6,1981-01-04,1981,1,4,6,Sunday,1981-01-05,1981-01-11,1980-12-28,1981-02-04
4,1981-01-05,15.8,1981-01-05,1981,1,5,0,Monday,1981-01-06,1981-01-12,1980-12-29,1981-02-05

In [20]:
df['minus month3'] = df['Date1'] - DateOffset(months=3)
df.head()

,Date,Temp,Date1,year,month,day,dayofweek,dayname,plus day1,plus day7,minus day7,plus month1,minus month3
0,1981-01-01,20.7,1981-01-01,1981,1,1,3,Thursday,1981-01-02,1981-01-08,1980-12-25,1981-02-01,1980-10-01
1,1981-01-02,17.9,1981-01-02,1981,1,2,4,Friday,1981-01-03,1981-01-09,1980-12-26,1981-02-02,1980-10-02
2,1981-01-03,18.8,1981-01-03,1981,1,3,5,Saturday,1981-01-04,1981-01-10,1980-12-27,1981-02-03,1980-10-03
3,1981-01-04,14.6,1981-01-04,1981,1,4,6,Sunday,1981-01-05,1981-01-11,1980-12-28,1981-02-04,1980-10-04
4,1981-01-05,15.8,1981-01-05,1981,1,5,0,Monday,1981-01-06,1981-01-12,1980-12-29,1981-02-05,1980-10-05

In [22]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1QVzVn7chK2dwl8zNZfhmXfuf-7ITrr9cow4AlGtFSnI/edit#gid=0

In [ ]:
df['plus year1'] = df['Date1'] + DateOffset(years=1)
df.head()

In [ ]:
df['minus year3'] = df['Date1'] - DateOffset(years=3)
df.head()

## **날짜 구간 데이터 만들기**
`pd.date_range(start=시작일자, end=종료일자, periods=기간수, freq=주기)`

|형식|설명|
|:--|:--|
|D|일별|
|W|주별|
|M|월별 말일|
|MS|월별 시작일|
|A|연도별 말일|
|AS|연도별 시작일|

In [23]:
pd.date_range(start='2020-01-01', periods=30, freq='D')
#하루씩 구간으로 날짜 구간을 구할 수 있음

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12',
               '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
               '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20',
               '2020-01-21', '2020-01-22', '2020-01-23', '2020-01-24',
               '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28',
               '2020-01-29', '2020-01-30'],
              dtype='datetime64[ns]', freq='D')

In [24]:
pd.date_range(start='2020-01-01', end='2023-06-30', freq='M')
#freq='M' 월단위로 나옴
#기본적으로 월 초랑 월말의 날짜가 나오는데

<ipython-input-24-e2413fa3d94e>:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  pd.date_range(start='2020-01-01', end='2023-06-30', freq='M')

DatetimeIndex(['2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30',
               '2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31',
               '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31',
               '2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30',
               '2021-05-31', '2021-06-30', '2021-07-31', '2021-08-31',
               '2021-09-30', '2021-10-31', '2021-11-30', '2021-12-31',
               '2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31',
               '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31',
               '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30'],
              dtype='datetime64[ns]', freq='ME')

In [25]:
pd.date_range(start='2020-01-01', end='2023-06-30', freq='MS')
#freq='MS' 이렇게 하면 각 1일만 나옴

DatetimeIndex(['2020-01-01', '2020-02-01', '2020-03-01', '2020-04-01',
               '2020-05-01', '2020-06-01', '2020-07-01', '2020-08-01',
               '2020-09-01', '2020-10-01', '2020-11-01', '2020-12-01',
               '2021-01-01', '2021-02-01', '2021-03-01', '2021-04-01',
               '2021-05-01', '2021-06-01', '2021-07-01', '2021-08-01',
               '2021-09-01', '2021-10-01', '2021-11-01', '2021-12-01',
               '2022-01-01', '2022-02-01', '2022-03-01', '2022-04-01',
               '2022-05-01', '2022-06-01', '2022-07-01', '2022-08-01',
               '2022-09-01', '2022-10-01', '2022-11-01', '2022-12-01',
               '2023-01-01', '2023-02-01', '2023-03-01', '2023-04-01',
               '2023-05-01', '2023-06-01'],
              dtype='datetime64[ns]', freq='MS')

In [27]:
pd.date_range(start='2020-01-01', end='2023-06-30', freq='A')
#freq='A' 연단위로 나오고 연말과 연초의 날짜가 나오는데

<ipython-input-27-1a7e4b58ef3f>:1: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  pd.date_range(start='2020-01-01', end='2023-06-30', freq='A')

DatetimeIndex(['2020-12-31', '2021-12-31', '2022-12-31'], dtype='datetime64[ns]', freq='YE-DEC')

In [28]:
pd.date_range(start='2020-01-01', end='2023-06-30', freq='AS')
# 연기준 1일날짜를 뽑고 싶을떄 AS

<ipython-input-28-601c91f6461a>:1: FutureWarning: 'AS' is deprecated and will be removed in a future version, please use 'YS' instead.
  pd.date_range(start='2020-01-01', end='2023-06-30', freq='AS')

DatetimeIndex(['2020-01-01', '2021-01-01', '2022-01-01', '2023-01-01'], dtype='datetime64[ns]', freq='YS-JAN')

## **기간 이동 계산**
`컬럼.rolling().집계함수`

In [29]:
df1 = data.copy()
df1.head()

         Date  Temp
0  1981-01-01  20.7
1  1981-01-02  17.9
2  1981-01-03  18.8
3  1981-01-04  14.6
4  1981-01-05  15.8

In [30]:
#7일 이동평균
df1['ma7'] = df1['Temp'].rolling(7).mean()
df1.head(20)
#.rolling(7).mean() 7일 이동평균을 구하는거임
#

          Date  Temp        ma7
0   1981-01-01  20.7        NaN
1   1981-01-02  17.9        NaN
2   1981-01-03  18.8        NaN
3   1981-01-04  14.6        NaN
4   1981-01-05  15.8        NaN
5   1981-01-06  15.8        NaN
6   1981-01-07  15.8  17.057143
7   1981-01-08  17.4  16.585714
8   1981-01-09  21.8  17.142857
9   1981-01-10  20.0  17.314286
10  1981-01-11  16.2  17.542857
11  1981-01-12  13.3  17.185714
12  1981-01-13  16.7  17.314286
13  1981-01-14  21.5  18.128571
14  1981-01-15  25.0  19.214286
15  1981-01-16  20.7  19.057143
16  1981-01-17  20.6  19.142857
17  1981-01-18  24.8  20.371429
18  1981-01-19  17.7  21.000000
19  1981-01-20  15.5  20.828571

In [31]:
df1['ma30'] = df1['Temp'].rolling(30).mean()
df1.head(30)
#30일 이동평균

          Date  Temp        ma7   ma30
0   1981-01-01  20.7        NaN    NaN
1   1981-01-02  17.9        NaN    NaN
2   1981-01-03  18.8        NaN    NaN
3   1981-01-04  14.6        NaN    NaN
4   1981-01-05  15.8        NaN    NaN
5   1981-01-06  15.8        NaN    NaN
6   1981-01-07  15.8  17.057143    NaN
7   1981-01-08  17.4  16.585714    NaN
8   1981-01-09  21.8  17.142857    NaN
9   1981-01-10  20.0  17.314286    NaN
10  1981-01-11  16.2  17.542857    NaN
11  1981-01-12  13.3  17.185714    NaN
12  1981-01-13  16.7  17.314286    NaN
13  1981-01-14  21.5  18.128571    NaN
14  1981-01-15  25.0  19.214286    NaN
15  1981-01-16  20.7  19.057143    NaN
16  1981-01-17  20.6  19.142857    NaN
17  1981-01-18  24.8  20.371429    NaN
18  1981-01-19  17.7  21.000000    NaN
19  1981-01-20  15.5  20.828571    NaN
20  1981-01-21  18.2  20.357143    NaN
21  1981-01-22  12.1  18.514286    NaN
22  1981-01-23  14.4  17.614286    NaN
23  1981-01-24  16.0  16.957143    NaN
24  1981-01-25  16.5  15.771429    NaN
25  1981-01-26  18.7  15.914286    NaN
26  1981-01-27  19.4  16.471429    NaN
27  1981-01-28  17.2  16.328571    NaN
28  1981-01-29  15.5  16.814286    NaN
29  1981-01-30  15.1  16.914286  17.79

- 평균 외에 합계, 최솟값, 최댓값 등 다양한 연산이 가능합니다.

In [32]:
df1['Temp'].rolling(7).sum()
#이동하면서 구간별 연산을 해야할

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
3645    91.7
3646    92.2
3647    92.5
3648    94.3
3649    97.3
Name: Temp, Length: 3650, dtype: float64

In [33]:
df1['Temp'].rolling(7).min()

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
3645    10.0
3646    10.0
3647    10.0
3648    10.0
3649    12.9
Name: Temp, Length: 3650, dtype: float64

In [34]:
df1['Temp'].rolling(7).max()

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
3645    14.6
3646    14.6
3647    14.6
3648    15.7
3649    15.7
Name: Temp, Length: 3650, dtype: float64

## **행 이동**
`컬럼.shift(이동할 행의 수)`

In [35]:
df2 = data.copy()

In [36]:
df2.head()

         Date  Temp
0  1981-01-01  20.7
1  1981-01-02  17.9
2  1981-01-03  18.8
3  1981-01-04  14.6
4  1981-01-05  15.8

In [37]:
df2['Temp shift1'] = df2['Temp'].shift(1)
df2.head()
#shift(1) 하면 한행씩 밀린걸 확인할 수 있음

         Date  Temp  Temp shift1
0  1981-01-01  20.7          NaN
1  1981-01-02  17.9         20.7
2  1981-01-03  18.8         17.9
3  1981-01-04  14.6         18.8
4  1981-01-05  15.8         14.6

In [38]:
df2['pct change'] = (df2['Temp shift1'] - df2['Temp'])/df2['Temp']
df2.head()
#ex. 전날대비 증감율이 얼마나 됐냐 이런걸 확인하려고할 땐
# (df2['Temp shift1'] - df2['Temp'])/df2['Temp'] 이렇게 해주면 됨

         Date  Temp  Temp shift1  pct change
0  1981-01-01  20.7          NaN         NaN
1  1981-01-02  17.9         20.7    0.156425
2  1981-01-03  18.8         17.9   -0.047872
3  1981-01-04  14.6         18.8    0.287671
4  1981-01-05  15.8         14.6   -0.075949

In [39]:
df2['Temp'].shift(7).head(10)
#이렇게 7을 넣게 되면 이렇게 7칸이 밀리게 되고

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7    20.7
8    17.9
9    18.8
Name: Temp, dtype: float64

In [40]:
df2['Temp'].shift(-1).head(10)
#양수뿐만 아니라 음수도 넣을 수 있음
# 이렇게 앞,뒤로 땡길 수 있음

0    17.9
1    18.8
2    14.6
3    15.8
4    15.8
5    15.8
6    17.4
7    21.8
8    20.0
9    16.2
Name: Temp, dtype: float64